[theme]
chartCategoricalColors = ["#006400","#99EE99", "#228B22","#FFD700","#FF4444","#CC0000","#8B0000"]
chartSequentialColors = ["#006400","#99EE99", "#228B22","#FFD700","#FF4444","#CC0000","#8B0000"]

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1FoikmJV86qN1rsGKRyhGqDFrBF1oj6oaRxqAkew2ATY/edit?pli=1&gid=0#gid=0"

# From your JSON key file
type= "service_account"
project_id= "encuestas-472023"
private_key_id= "2de2dfa28911b36ee08810d339afc35f8060ed49"
private_key= "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC07S2oYKvwJTfy\n1U6XdZvzjhA+qApe2JzExj/yQSHm9v1saQ/uiwlt4Yx9FYS1rSnAp53OmdrIrtA9\nzlSByRH69YcijM6A9mDZTZvBJiwwj/b01BMGhYMqZ5gPSTaXBjnm3Ge20AGVJlIH\nm01AfDrBYD4DWlalw5udfMIKjZuUE8DIIF1s75MmShTCtrrwUNaw4hMzx05HeIbK\nCjKhquxRvHhwy8GykAkWvRY8Jw9pvpcjJYZ7dWXJkuZ3KEe6Npaeug/iY3pqa/Z7\nIBWYutHWH/oiPyvKpeuuyDWaVhCffy9q2O+rVuOWSdKovS9HX4PtTODxfvhrn71c\n4pgbmIDNAgMBAAECggEAAjcJIQ+V60m5W/Vf50Ye/lCrQukcag7YKdHiLzK8RISa\nPlKG9Geqr41cV/JZ0+jmeEpVCet48eNZ/00LByURXZ4rOlwORyaSXEwGmnW/gr9b\nHveIXW29rlji/q+UcILjVeqK29fDZ90L52CaWy4U1hCPPHabAEqFxDF7z/9DJqvr\nRxPPHvALJQ161dypPZgJDfsuizY5iF/LxrnU1KLW0RcjJ7nPk7RaXm2KKUVPC3X6\nMpzfgvRTL2aEvEWRJEOVfqvqozz6FhQWbZnSxbXg9onunw2Gcwban8xjb0bKD1YJ\nzxvyLmCLA/0TbssVD9rIp7pTO/y0PepDWwlGcR6CbQKBgQDsOhpN2RfOvblcVRwj\nbZclsrCNSTsE/1mSVfSF43cNMzssmkM5n5xncdvh2Tcw6DcCaLPbzPQx+eNrtu8b\nxOJtmEbD65QNQkxgejBXOAZCF+pHRqId7nIXad/OD2UJzTcZF6BnINP3EwKfH3T6\nz0CEzAYXYa3/qdd/DeBVKDEN0wKBgQDEEhc6M25ysi1rUSeWeNo+BC4qN7rzr7at\ndBp+94ccS+8ViJW6v3v0/bduaUZXuDCVf0mH2g6BbshuDhYMbKRS2R4c57lp145a\npljPpl+v1fXwp+CkmpcQk+049Yuq/uuCwvkonFxnZcnHadlSROgPc7WEOV4/EuCe\ndzkYY4Ty3wKBgQCS2afifzOqpQznFk2wxH7yw3u3yS90ct0W+HJTDU3EGfYOSzPB\nTbToJcLgSq1hrOoNiFNPL8EalFLJcmaAZ8uu/7v2LavS9kUOsMb+YWiai81rU8CS\nRNoOLhYgPje8eSNoaOShV6oNbXbyvpZ1GIPuSfr7bBDD36yEYnbz2VFtWwKBgCdB\nO/dCDs3V0HQY9mUQ4xjhe2Cmcb6SIm/Nu/RJmHpY1ZApHVkbNzUQiuYHG7c6QDfe\nGRmi1Z6iUGyAU3e/VJLltzqwRhXjuzN49HT2aVfp7Wh2I+qwrKf8BdWOi5z7lqlC\nYeH4lCN7ZI+RKJppA1D8qI3FcpIMNH5lfj/cxORfAoGAUpAPf62neGD/pblGx5lJ\nRrEZOuoHn+tcC2W03mDXpi1OyYH1zImt8Qx7kvSbK1XZfq/zjMnYsmI8vbMJE4eX\nRaovQAzdwArQG2a0NhzF5eF8Exh7ku8MispXIlmiHNsaZBlrqvQq5w45RWZLRrMC\n5PS1fXnIg76i7DZEhctKj6c=\n-----END PRIVATE KEY-----\n"
client_email= "service-acc@encuestas-472023.iam.gserviceaccount.com"
client_id= "115847165664408607793"
auth_uri= "https://accounts.google.com/o/oauth2/auth"
token_uri= "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url= "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url= "https://www.googleapis.com/robot/v1/metadata/x509/service-acc%40encuestas-472023.iam.gserviceaccount.com"


[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "AlejandRoHIjoMio30122023"
client_id = "1095203158754-bbcti0lt1d7nndl7pek7g6isdqmce142.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"